# -*- coding: utf-8 -*-
"""PPEC-iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0Al9Il2hwV8uylcYqU-bymFE7DwJUsR
"""

#IMPORTAÇÕES
!pip install ucimlrepo
!pip install lime

import numpy as np
import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
import shap
from lime import lime_tabular

from sklearn.linear_model    import LogisticRegression
from sklearn.neighbors       import KNeighborsClassifier
from sklearn.tree            import DecisionTreeClassifier, plot_tree
from sklearn.ensemble        import RandomForestClassifier
from sklearn.cluster         import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.preprocessing   import LabelEncoder, StandardScaler
from sklearn.decomposition   import PCA
from scipy.cluster.hierarchy     import dendrogram, linkage
from sklearn.model_selection import StratifiedKFold, cross_val_predict, train_test_split, learning_curve
from sklearn.metrics         import (
    f1_score, roc_auc_score, accuracy_score,
    confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc
)
from xgboost import XGBClassifier
import xgboost as xgb

from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)

df = pd.concat([X, y], axis=1)
print(df.columns)
print(df.head())

# INSERIR RUÍDO
RANDOM_STATE = 42

def aplicar_mixup(df, coluna_alvo="class", n_amostras_novas=850, alpha=0.2, random_state=RANDOM_STATE):
    rng = np.random.default_rng(random_state)
    X = df.drop(columns=[coluna_alvo]).values
    y = df[coluna_alvo].values

    novas_X, novas_y = [], []
    for _ in range(n_amostras_novas):
        i, j = rng.integers(0, len(df), size=2)
        lam = rng.beta(alpha, alpha)
        x_novo = lam * X[i] + (1 - lam) * X[j]
        y_novo = y[i] if lam >= 0.5 else y[j]
        novas_X.append(x_novo)
        novas_y.append(y_novo)

    df_novos = pd.DataFrame(novas_X, columns=df.drop(columns=[coluna_alvo]).columns)
    df_novos[coluna_alvo] = novas_y

    return pd.concat([df, df_novos], ignore_index=True)

def inserir_ruido_gaussiano(df, proporcao, coluna_alvo="class", random_state=RANDOM_STATE):
    rng = np.random.default_rng(random_state)
    df_ruidoso = df.copy()

    colunas_numericas = df.select_dtypes(include=[np.number]).columns.tolist()
    colunas_numericas = [c for c in colunas_numericas if c != coluna_alvo]

    for col in colunas_numericas:
        desvio_padrao = df[col].std()
        ruido = rng.normal(loc=0.0, scale=desvio_padrao * proporcao, size=len(df))
        df_ruidoso[col] = df[col] + ruido

    return df_ruidoso

iris_baixo  = inserir_ruido_gaussiano(df, proporcao=0.10)
iris_medio  = inserir_ruido_gaussiano(df, proporcao=0.20)
iris_alto   = inserir_ruido_gaussiano(df, proporcao=0.30)

iris_base_mixup  = aplicar_mixup(df)
iris_baixo_mixup  = aplicar_mixup(iris_baixo)
iris_medio_mixup  = aplicar_mixup(iris_medio)
iris_alto_mixup   = aplicar_mixup(iris_alto)

for nome, dataset in [
    ("base_mixup",   iris_base_mixup),
    ("baixo_mixup", iris_baixo_mixup),
    ("medio_mixup", iris_medio_mixup),
    ("alto_mixup",  iris_alto_mixup),
]:
    print(f"{nome:15s} -> {len(dataset)} amostras | classes: {dict(Counter(dataset['class']))}")

# MODELOS
COLUNA_ALVO  = "class"

def preparar_dados(df, coluna_alvo=COLUNA_ALVO):
    X = df.drop(columns=[coluna_alvo])
    y = df[coluna_alvo]
    le = LabelEncoder()
    y_enc = le.fit_transform(y)
    return X, y_enc, le

def definir_modelos():
    return {
        "Regressão Logística": LogisticRegression(max_iter=1000, random_state=RANDOM_STATE),
        "KNN":                 KNeighborsClassifier(),
        "Decision Tree":       DecisionTreeClassifier(random_state=RANDOM_STATE),
        "Random Forest":       RandomForestClassifier(random_state=RANDOM_STATE),
        "XGBoost":             XGBClassifier(eval_metric="mlogloss", random_state=RANDOM_STATE),
    }

def separar_dados(df, coluna_alvo=COLUNA_ALVO):
    X, y, le = preparar_dados(df, coluna_alvo)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
    )
    return X_train, X_test, y_train, y_test, le

def avaliar_modelos(df, coluna_alvo=COLUNA_ALVO, k=5):
    X, y, le = preparar_dados(df, coluna_alvo)
    modelos   = definir_modelos()
    cv        = StratifiedKFold(n_splits=k, shuffle=True, random_state=RANDOM_STATE)
    resultados = []

    fig_cm, eixos = plt.subplots(1, len(modelos), figsize=(6.5 * len(modelos), 4.5), gridspec_kw={'wspace': 0.6})
    fig_roc, ax_roc = plt.subplots(figsize=(8, 4))

    for idx, (nome, modelo) in enumerate(modelos.items()):
        y_pred = cross_val_predict(modelo, X, y, cv=cv)
        y_prob = cross_val_predict(modelo, X, y, cv=cv, method="predict_proba")

        f1      = f1_score(y, y_pred, average="weighted")
        auc_roc = roc_auc_score(y, y_prob, multi_class="ovr", average="weighted")
        acc     = accuracy_score(y, y_pred)

        resultados.append({"Modelo": nome, "F1-Score": f1,
                            "AUC-ROC": auc_roc, "Acurácia": acc})

        # Matriz de confusão
        cm = confusion_matrix(y, y_pred)

        # O truque para a caixa ficar menor dentro do subgráfico:
        # Usamos o parâmetro ax=eixos[idx] e depois ajustamos a posição interna
        disp = ConfusionMatrixDisplay(cm, display_labels=le.classes_)
        disp.plot(ax=eixos[idx], colorbar=False)

        # ALTERAÇÃO 1: Deixa os quadrados menores dentro do espaço disponível
        eixos[idx].set_box_aspect(1) # Força a caixa a ser perfeitamente quadrada

        # ALTERAÇÃO 2: Aumenta o tamanho da fonte do título do modelo
        eixos[idx].set_title(nome, fontsize=14, pad=10)

        # ALTERAÇÃO 3: Aumenta o tamanho dos rótulos dos eixos (Iris-setosa, etc)
        eixos[idx].tick_params(axis='both', which='major', labelsize=12)
        eixos[idx].xaxis.label.set_size(12)
        eixos[idx].yaxis.label.set_size(12)

        # Opcional: Oculta o rótulo do eixo Y a partir do segundo gráfico para limpar o visual
        if idx > 0:
            eixos[idx].set_ylabel('')

        # Curva ROC (OvR para multiclasse)
        for i, classe in enumerate(le.classes_):
            fpr, tpr, _ = roc_curve((y == i).astype(int), y_prob[:, i])
            ax_roc.plot(fpr, tpr, label=f"{nome} – {classe} (AUC={auc(fpr,tpr):.2f})")

    ax_roc.plot([0,1],[0,1],"k--")
    ax_roc.set_xlabel("FPR"); ax_roc.set_ylabel("TPR")
    ax_roc.set_title("Curvas ROC"); ax_roc.legend(fontsize=7)
    plt.tight_layout(); plt.show()

    return pd.DataFrame(resultados).set_index("Modelo")

def plotar_correlacao(df, coluna_alvo=COLUNA_ALVO):
    numericas = df.drop(columns=[coluna_alvo]).select_dtypes(include=[np.number])
    plt.figure(figsize=(7, 5))
    sns.heatmap(numericas.corr(), annot=True, fmt=".2f", cmap="coolwarm")
    plt.title("Matriz de Correlação"); plt.tight_layout(); plt.show()

def plotar_shap(df, coluna_alvo=COLUNA_ALVO):
    """
    Gera SHAP summary plot usando Random Forest como modelo base.
    Registra os 10 atributos mais relevantes.
    """
    X, y, _ = preparar_dados(df, coluna_alvo)
    modelo = RandomForestClassifier(random_state=RANDOM_STATE).fit(X, y)
    explainer   = shap.TreeExplainer(modelo)
    shap_values = explainer.shap_values(X)
    shap.summary_plot(shap_values, X, plot_type="bar", max_display=10)

def plotar_lime(df, indice_amostra=0, coluna_alvo=COLUNA_ALVO):
    """
    Gera explicação LIME para uma amostra específica.
    Parâmetro indice_amostra define qual linha do dataset será explicada.
    """
    X, y, le = preparar_dados(df, coluna_alvo)
    modelo = RandomForestClassifier(random_state=RANDOM_STATE).fit(X, y)
    explainer = lime_tabular.LimeTabularExplainer(
        X.values,
        feature_names=X.columns.tolist(),
        class_names=le.classes_,
        discretize_continuous=True,
        random_state=RANDOM_STATE,
    )
    exp = explainer.explain_instance(
        X.values[indice_amostra], modelo.predict_proba, num_features=10
    )
    exp.show_in_notebook(show_table=True)

def plotar_correlacao_train_test(X_train, X_test):
    fig, eixos = plt.subplots(1, 2, figsize=(14, 5))
    sns.heatmap(X_train.corr(), annot=True, fmt=".2f",
                cmap="coolwarm", ax=eixos[0])
    eixos[0].set_title("Correlação – Treino (80%)")
    sns.heatmap(X_test.corr(), annot=True, fmt=".2f",
                cmap="coolwarm", ax=eixos[1])
    eixos[1].set_title("Correlação – Teste (20%)")
    plt.tight_layout(); plt.show()

def plotar_coeficientes_regressao(X_train, y_train, le):
    modelo = LogisticRegression(
        max_iter=1000, random_state=RANDOM_STATE
    ).fit(X_train, y_train)
    coef_df = pd.DataFrame(
        modelo.coef_, columns=X_train.columns, index=le.classes_
    )
    coef_df.T.plot(kind="barh", figsize=(8, 5))
    plt.title("Coeficientes – Regressão Logística")
    plt.xlabel("Valor do coeficiente")
    plt.axvline(0, color="black", linewidth=0.8, linestyle="--")
    plt.tight_layout(); plt.show()

def plotar_fronteira_knn(X_train, X_test, y_train, y_test, le, n_vizinhos=5):
    pca     = PCA(n_components=2, random_state=RANDOM_STATE)
    Xtr_2d  = pca.fit_transform(X_train)
    Xte_2d  = pca.transform(X_test)
    var     = pca.explained_variance_ratio_
    label_pc1 = f"PC1 ({var[0]:.1%} da variância)"
    label_pc2 = f"PC2 ({var[1]:.1%} da variância)"

    modelo  = KNeighborsClassifier(n_neighbors=n_vizinhos).fit(Xtr_2d, y_train)

    h = 0.05
    x_min, x_max = Xtr_2d[:, 0].min() - 0.5, Xtr_2d[:, 0].max() + 0.5
    y_min, y_max = Xtr_2d[:, 1].min() - 0.5, Xtr_2d[:, 1].max() + 0.5
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    Z = modelo.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

    plt.figure(figsize=(8, 5))
    plt.contourf(xx, yy, Z, alpha=0.3, cmap="tab10")
    scatter = plt.scatter(Xte_2d[:, 0], Xte_2d[:, 1],
                          c=y_test, cmap="tab10", edgecolors="k", s=40)
    plt.legend(handles=scatter.legend_elements()[0], labels=list(le.classes_))
    plt.title(f"Fronteira de Decisão – KNN (k={n_vizinhos})\n"
              f"Variância total explicada: {sum(var):.1%}")
    plt.xlabel(label_pc1); plt.ylabel(label_pc2)
    plt.tight_layout(); plt.show()

def plotar_arvore(X_train, X_test, y_train, y_test, le, max_depth=2):
    modelo = DecisionTreeClassifier(
        max_depth=max_depth, random_state=RANDOM_STATE
    ).fit(X_train, y_train)
    acc_train = accuracy_score(y_train, modelo.predict(X_train))
    acc_test  = accuracy_score(y_test,  modelo.predict(X_test))
    plt.figure(figsize=(8, 5))
    plot_tree(modelo, feature_names=X_train.columns.tolist(),
              class_names=le.classes_, filled=True, rounded=True, fontsize=9)
    plt.title(f"Árvore de Decisão (max_depth={max_depth})\n"
              f"Acurácia treino: {acc_train:.2%} | teste: {acc_test:.2%}")
    plt.tight_layout(); plt.show()

def plotar_importancia_random_forest(X_train, X_test, y_train, y_test):
    modelo = RandomForestClassifier(max_depth=4,
        random_state=RANDOM_STATE
    ).fit(X_train, y_train)
    acc_train = accuracy_score(y_train, modelo.predict(X_train))
    acc_test  = accuracy_score(y_test,  modelo.predict(X_test))
    importancias = pd.Series(
        modelo.feature_importances_, index=X_train.columns
    ).sort_values()
    plt.figure(figsize=(7, 4))
    sns.barplot(x=importancias.values, y=importancias.index, palette="Blues_r")
    plt.title(f"Importância dos Atributos – Random Forest\n"
              f"Acurácia treino: {acc_train:.2%} | teste: {acc_test:.2%}")
    plt.xlabel("Importância média (Gini)")
    plt.tight_layout(); plt.show()

def plotar_artefatos_xgboost(X_train, X_test, y_train, y_test):
    modelo = XGBClassifier(
        eval_metric="mlogloss",
        random_state=RANDOM_STATE,
        early_stopping_rounds=10,
    ).fit(X_train, y_train,
          eval_set=[(X_train, y_train), (X_test, y_test)],
          verbose=False)
    acc_train = accuracy_score(y_train, modelo.predict(X_train))
    acc_test  = accuracy_score(y_test,  modelo.predict(X_test))
    fig, eixos = plt.subplots(1, 2, figsize=(14, 5))
    xgb.plot_importance(modelo, ax=eixos[0],
                        title=f"Feature Importance – XGBoost\n"
                              f"Acurácia treino: {acc_train:.2%} | teste: {acc_test:.2%}")
    resultados = modelo.evals_result()
    eixos[1].plot(resultados["validation_0"]["mlogloss"], label="Treino")
    eixos[1].plot(resultados["validation_1"]["mlogloss"], label="Teste")
    eixos[1].set_title("Learning Curve – XGBoost (mlogloss)")
    eixos[1].set_xlabel("Iterações"); eixos[1].set_ylabel("Log Loss")
    eixos[1].legend()
    plt.tight_layout(); plt.show()

def plotar_real_vs_previsto(X_train, X_test, y_train, y_test, le):
    modelos = definir_modelos()
    pca     = PCA(n_components=2, random_state=RANDOM_STATE)
    Xtr_2d  = pca.fit_transform(X_train)
    Xte_2d  = pca.transform(X_test)
    var     = pca.explained_variance_ratio_
    label_pc1 = f"PC1 ({var[0]:.1%} da variância)"
    label_pc2 = f"PC2 ({var[1]:.1%} da variância)"

    fig, eixos = plt.subplots(len(modelos), 2,
                              figsize=(12, 4 * len(modelos)))

    for linha, (nome, modelo) in enumerate(modelos.items()):
        modelo.fit(X_train, y_train)
        for coluna, (X_2d, X_orig, y_real, rotulo) in enumerate([
            (Xtr_2d, X_train, y_train, "Treino"),
            (Xte_2d, X_test,  y_test,  "Teste"),
        ]):
            y_pred  = modelo.predict(X_orig)
            acertos = y_pred == y_real
            ax      = eixos[linha][coluna]
            ax.scatter(X_2d[acertos, 0],  X_2d[acertos, 1],
                       c="green", alpha=0.6, s=40, label="Acerto",
                       edgecolors="k", linewidths=0.3)
            ax.scatter(X_2d[~acertos, 0], X_2d[~acertos, 1],
                       c="red", alpha=0.9, s=60, label="Erro",
                       marker="X", edgecolors="k", linewidths=0.3)
            acc = accuracy_score(y_real, y_pred)
            ax.set_title(f"{nome} – {rotulo} | Acurácia: {acc:.2%}")
            ax.set_xlabel(label_pc1); ax.set_ylabel(label_pc2)
            ax.legend(fontsize=8)

    plt.suptitle(f"Acertos e Erros por Modelo (PCA 2D)\n"
                 f"Variância total explicada: {sum(var):.1%}",
                 fontsize=13, y=1.01)
    plt.tight_layout(); plt.show()

# CLUSTERING
def plot_clusters(data, label_col, title, x_col="petal length", y_col="petal width"):
    plt.figure(figsize=(7, 6))
    sns.scatterplot(data=data, x=x_col, y=y_col, hue=label_col, palette="tab10", s=70)
    plt.title(title)
    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.grid(True)
    plt.legend(title="Cluster")
    plt.show()

def plotar_KMeans(df, coluna_alvo=COLUNA_ALVO, n_clusters=3):
    X, _, _ = preparar_dados(df, coluna_alvo)
    scaler  = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_2d    = PCA(n_components=2, random_state=RANDOM_STATE).fit_transform(X_scaled)

    modelo  = KMeans(n_clusters=n_clusters, random_state=RANDOM_STATE, n_init="auto")
    labels  = modelo.fit_predict(X_2d)

    plt.figure(figsize=(7, 5))
    scatter = plt.scatter(X_2d[:, 0], X_2d[:, 1], c=labels, cmap="tab10", edgecolors="k", s=40)
    centroids_2d = modelo.cluster_centers_
    plt.scatter(centroids_2d[:, 0], centroids_2d[:, 1],
                marker="o", s=200, c="black", zorder=5, label="Centróides")
    plt.title(f"K-Means (k={n_clusters}, PCA 2D)")
    plt.xlabel("PC1"); plt.ylabel("PC2")
    plt.legend(); plt.tight_layout(); plt.show()


def plotar_Hierarquical(df, coluna_alvo=COLUNA_ALVO, n_clusters=3):
    X, _, _ = preparar_dados(df, coluna_alvo)
    scaler   = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_2d     = PCA(n_components=2, random_state=RANDOM_STATE).fit_transform(X_scaled)

    # Dendrograma
    ligacao = linkage(X_scaled, method="ward")
    plt.figure(figsize=(12, 4))
    dendrogram(ligacao, truncate_mode="lastp", p=30,
               leaf_rotation=90, leaf_font_size=8)
    plt.title("Dendrograma – Hierarchical Clustering (Ward)")
    plt.xlabel("Amostras"); plt.ylabel("Distância")
    plt.tight_layout(); plt.show()

    # Clusters em 2D
    modelo = AgglomerativeClustering(n_clusters=n_clusters)
    labels = modelo.fit_predict(X_scaled)
    plt.figure(figsize=(7, 5))
    plt.scatter(X_2d[:, 0], X_2d[:, 1], c=labels, cmap="tab10", edgecolors="k", s=40)
    plt.title(f"Hierarchical Clustering (k={n_clusters}, PCA 2D)")
    plt.xlabel("PC1"); plt.ylabel("PC2")
    plt.tight_layout(); plt.show()

def plotar_DBSCAN(df, coluna_alvo=COLUNA_ALVO, eps=0.5, min_samples=5):
    X, _, _ = preparar_dados(df, coluna_alvo)
    scaler   = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_2d     = PCA(n_components=2, random_state=RANDOM_STATE).fit_transform(X_scaled)

    modelo = DBSCAN(eps=eps, min_samples=min_samples)
    labels = modelo.fit_predict(X_scaled)

    n_clusters  = len(set(labels)) - (1 if -1 in labels else 0)
    n_ruido     = list(labels).count(-1)

    plt.figure(figsize=(8, 6))
    plt.scatter(X_2d[:, 0], X_2d[:, 1], c=labels, cmap="tab10", edgecolors="k", s=40)
    plt.title(f"DBSCAN (eps={eps}, min_samples={min_samples})\n"
              f"{n_clusters} clusters | {n_ruido} pontos de ruído")
    plt.xlabel("PC1"); plt.ylabel("PC2")
    plt.tight_layout(); plt.show()

def plotar_elbow(df, coluna_alvo=COLUNA_ALVO, k_max=10):
    X, _, _ = preparar_dados(df, coluna_alvo)
    inercias = []
    ks = range(1, k_max + 1)
    for k in ks:
        km = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init="auto")
        km.fit(X)
        inercias.append(km.inertia_)
    plt.figure(figsize=(6, 4))
    plt.plot(ks, inercias, "bo-")
    plt.xlabel("Número de clusters (k)")
    plt.ylabel("Inércia")
    plt.title("Elbow Curve – K-Means")
    plt.xticks(ks)
    plt.tight_layout(); plt.show()

def executar_pipeline(df, nome_dataset="dataset", coluna_alvo=COLUNA_ALVO):
    print(f"\n{'='*60}")
    print(f"  PIPELINE: {nome_dataset} | {len(df)} amostras")
    print(f"{'='*60}\n")
    print("\n")

    X_train, X_test, y_train, y_test, le = separar_dados(df, coluna_alvo)

    print("== ENTENDIMENTO DOS DADOS ==================================")
    display(df.describe())
    sns.countplot(data=df, x=coluna_alvo); plt.tight_layout(); plt.show()
    plotar_correlacao(df, coluna_alvo)
    plotar_correlacao_train_test(X_train, X_test)

    print("== CLASSIFICAÇÃO ===========================================")
    metricas = avaliar_modelos(df, coluna_alvo)
    display(metricas)
    metricas.plot(kind="bar", figsize=(9, 5),
                  title="Comparativo de Métricas")
    plt.tight_layout(); plt.show()
    plotar_real_vs_previsto(X_train, X_test, y_train, y_test, le)

    print("== ARTEFATOS POR MODELO ====================================")
    plotar_coeficientes_regressao(X_train, y_train, le)
    plotar_fronteira_knn(X_train, X_test, y_train, y_test, le)
    plotar_arvore(X_train, X_test, y_train, y_test, le)
    plotar_importancia_random_forest(X_train, X_test, y_train, y_test)
    plotar_artefatos_xgboost(X_train, X_test, y_train, y_test)

    print("== EXPLICABILIDADE =========================================")
    plotar_shap(df, coluna_alvo)
    plotar_lime(df, indice_amostra=0, coluna_alvo=coluna_alvo)

    print("== CLUSTERIZAÇÃO ===========================================")
    plotar_elbow(df, coluna_alvo)
    plotar_KMeans(df, coluna_alvo)
    plotar_Hierarquical(df, coluna_alvo)
    plotar_DBSCAN(df, coluna_alvo)

    return metricas

metricas = executar_pipeline(iris_base_mixup, nome_dataset="base_mixup")

metricas = executar_pipeline(iris_baixo_mixup, nome_dataset="baixo_mixup")

metricas = executar_pipeline(iris_medio_mixup, nome_dataset="medio_mixup")

metricas = executar_pipeline(iris_alto_mixup, nome_dataset="alto_mixup")